# Generated by Django 2.1.5 on 2019-01-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190129_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dead_line',
            field=models.DateTimeField(),
        ),
    ]
