# Generated by Django 2.1.5 on 2019-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190129_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='message_html',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
