# Generated by Django 2.1.5 on 2019-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190131_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='current_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='dead_line',
            field=models.DateField(),
        ),
    ]
